### ISSUE TITLE
Can you upload it to Maven? Cant do it by myself cause license

### ISSUE THREAD

**Issue by Meinval** [vaadin/vaadin-autocomplete#17]

**Comment by Peppe** [comment]
Hi!

Are you looking for a webjar packaging of the components, so that you can use it in templates within Vaadin Flow? Is jar enough or do you need Java APIs as well?

Incubator is a platform for customers of Vaadin can inexpensively order new capabilities. The customer specifies what is needed and Vaadin builds it. Consultancy prices are radically cut down due to Vaadin owning the sources after the product. All components are available for all Prime customers, and any customer can order more features on top of any component. Incubator-autocomplete was built as a web component, and building additional features, like Java API, is available to order. You can read more on incubator at https://vaadin.com/support#incubator. If you are interested in sponsoring further development of autocomplete, you can contact me at jens _at_ vaadin.com

**Comment by Skrikjo** [comment]
Hi!
Here is link to webjar for this web-component in Maven: [https://mvnrepository.com/artifact/com.vaadin.webjar/incubator-autocomplete](https://mvnrepository.com/artifact/com.vaadin.webjar/incubator-autocomplete)

Also here is Java API for this incubator-autocomplete component: [https://github.com/vaadin/incubator-autocomplete-flow](https://github.com/vaadin/incubator-autocomplete-flow)
